### ISSUE TITLE
[Feature request] Add prefix/suffix to measurement name

### ISSUE THREAD

**Issue by wei-hai** [creditkarma/good-influx#5]
When multiple projects adopt good-influx, they will send metrics to the same measurement, e.g., `ops`, which is not convenient. I suggest that we could support prefix/suffix in config file to make the measurement name based on project, e.g., when adding prefix `{prefix: projectABC}` it shall send metrics to measurement `projectABC_ops`. The default prefix could be `empty` or `good_influx`.

**Comment by fhemberger** [comment]
Thank you, that's a good point. Will look into it!
