### ISSUE TITLE
Maintainers wanted

### ISSUE THREAD

**Issue by fhemberger** [creditkarma/good-influx#9]
I could use a little help maintaining this module, as I'm unfortunately quite busy with other things. 

**Any help is appreciated**, I'd like to see the module being kept up with new developments on the InfluxDB API side and best practices revolving around them. If you'd like to help, please get in touch.

**Comment by AlecHFerguson** [comment]
@fhemberger I can help.  I think you already made me a collaborator, no?

Are there specific changes or improvements you would like to see made to the module?  There are currently 4 issues open.  My team has actually been working on the oldest of them, and may have a PR out soon. We filed two others, both of which we may work on in the near future.  Maybe file issues for any other changes or improvements you would like to make?

**Comment by fhemberger** [comment]
@AlecHFerguson Yes, I invited you (but you still have to confirm) ;)

It's basically that I haven't been using InfluxDB in client projects lately, so I'm a bit out of touch and cautious about accepting change requests – I don't want to break the library for people like you, who are already using it. So it would be good to have someone with more experience on board to see if proposed changes make sense, follow InfluxDB's best practices and don't introduce breaking changes by accident (i.e. without explicit major version change on the module).

**Comment by AlecHFerguson** [comment]
Confirmed 👍 

I wouldn't consider myself an "expert" on InfluxDB, per se; but my company uses it a lot, so there are several experts I can turn to for advice as needed.  I am actively using this module in production, so I'll have a good sense of whether changes are breaking (at least for my usages).

You've seen my contributions, comments on PR's and issues, etc.  Based on that if you'd like me to take a more active role as maintainer then I would be honored.

**Comment by fhemberger** [comment]
Closing this issue for now, thanks to @AlecHFerguson and @sfabriece for your help!

**Comment by fhemberger** [comment]
After giving it some thought, I decided to re-open this issue:

> I stopped using `good` a long time ago for logging in my own projects and haven't had the chance to work with hapi in general for a while now, so I'd like to hand over the project to someone who is more committed in maintaining it.
>
> The project is considered feature complete, the only greater change I see right now is ensuring its compatibility with [good's recent adaption](https://github.com/hapijs/good/pull/572) of the `async`/`await` pattern (already started in #30).
>
> So if anyone is interested, I'd be more than grateful to see this project thriving in a new home.

**Comment by nnance** [comment]
@fhemberger I work with @AlecHFerguson and we work for Credit Karama.  We have a GitHub organization where we are doing a lot of work with Hapi and we would be willing to take over the project if you would be willing to transfer it to our GitHub organization.

Thoughts?

**Comment by fhemberger** [comment]
@nnance This would be really awesome as I know the project would be in best hands.

To transfer a repo to an organization, I'd require the right to create new repos there, so the easier way would be to transfer the repo to either you or @AlecHFerguson first and you move it to the org afterwards. I also need an npm user to transfer publishing rights.

**Comment by AlecHFerguson** [comment]
@fhemberger We would be honored to take this on. Credit Karma uses Good Influx in several production Node.js services so we'll definitely support it for the long term. At least one CK developer has a pretty cool log event reporter in the works, and we will probably have other features as well.

I will speak with our open source committee next week to get an account that we can transfer this to.

**Comment by fhemberger** [comment]
Awesome! :100:

**Comment by nnance** [comment]
@fhemberger you can transfer the repo to me.  You can transfer publishing rights to nnanceck

**Comment by fhemberger** [comment]
@nnance Requested the transfer on GitHub, you're already owner on npm. Thank you!

**Comment by fhemberger** [comment]
@nnance Could you please accept the transfer?

**Comment by nnance** [comment]
@fhemberger I am totally sorry.  All of my Github emails were in my spam folder.  I tried accepting and it told me it timed out.  If you will do the transfer again I will monitor it more closely

**Comment by fhemberger** [comment]
@nnance I just renewed the request.
